// Auto-generated by gcrecomp recompiler
#include "gcrecomp/runtime.h"
#include "gcrecomp/ppc_helpers.h"
#include <cstring>  // std::memcpy/std::memset used in recompiled code

using gcrecomp::PPCContext;
using gcrecomp::Memory;
using gcrecomp::FuncTable;
using gcrecomp::g_mem;
using gcrecomp::g_func_table;

// Memory access macros
#define MEM_READ8(addr)         g_mem.read8(static_cast<uint32_t>(addr))
#define MEM_READ16(addr)        g_mem.read16(static_cast<uint32_t>(addr))
#define MEM_READ32(addr)        g_mem.read32(static_cast<uint32_t>(addr))
#define MEM_READF32(addr)       g_mem.readf32(static_cast<uint32_t>(addr))
#define MEM_READF64(addr)       g_mem.readf64(static_cast<uint32_t>(addr))
#define MEM_WRITE8(addr, val)   g_mem.write8(static_cast<uint32_t>(addr), static_cast<uint8_t>(val))
#define MEM_WRITE16(addr, val)  g_mem.write16(static_cast<uint32_t>(addr), static_cast<uint16_t>(val))
#define MEM_WRITE32(addr, val)  g_mem.write32(static_cast<uint32_t>(addr), static_cast<uint32_t>(val))
#define MEM_WRITEF32(addr, val) g_mem.writef32(static_cast<uint32_t>(addr), static_cast<float>(val))
#define MEM_WRITEF64(addr, val) g_mem.writef64(static_cast<uint32_t>(addr), static_cast<double>(val))

// Indirect call macro
#define CALL_INDIRECT(addr, ctx, mem) g_func_table.call(static_cast<uint32_t>(addr), ctx, mem)

// Function-entry trace disabled (rebuild with --trace to enable)
#define TRACE_ENTER(addr) ((void)0)

// PSQ wrapper macros (delegate to gcrecomp runtime helpers with g_mem)
#define PSQ_LOAD_ONE(addr, gqr)              psq_load_one(g_mem, static_cast<uint32_t>(addr), gqr)
#define PSQ_LOAD_PAIR(ps0, ps1, addr, gqr)   psq_load_pair(g_mem, ps0, ps1, static_cast<uint32_t>(addr), gqr)
#define PSQ_STORE_ONE(val, addr, gqr)         psq_store_one(g_mem, val, static_cast<uint32_t>(addr), gqr)
#define PSQ_STORE_PAIR(v0, v1, addr, gqr)     psq_store_pair(g_mem, v0, v1, static_cast<uint32_t>(addr), gqr)
